<?php

namespace App\Http\Controllers;

use App\Models\Event;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Inertia\Inertia;
use App\Models\Company;
use App\Models\TicketCategory;
use App\Models\Participant;
use Carbon\Carbon;
use Carbon\CarbonPeriod;

use function Symfony\Component\String\b;

class ParticipantController extends Controller
{
    /**
     * Store a new participant for an event.
     */
    public function store(Request $request, Event $event)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email',
            'phone' => 'required|string|max:20',
            'company_name' => 'nullable|string|max:255',
            'company_logo' => 'nullable|image|max:2048',
        ]);

        $company = Company::firstOrCreate(
            ['name' => $validated['company_name']]
        );

        $company->update([
            'company_logo' => $validated['company_logo']->store('companies', 'public'),
        ]);

        $companyId = $company->id;

        $user = Auth::user();
        $organizer = $user->organizer;

        // Verify organizer owns this event
        if ($event->organizer_id != $organizer->id) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }


        // Create or find user by email
        $userPIC = User::firstOrCreate(
            ['email' => $validated['email']],
            [
                'name' => $validated['name'],
                'phone' => $validated['phone'] ?? null,
                'company_id' => $companyId,
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]
        );
        if (is_null($userPIC->company_id)) {
            $userPIC->company_id = $companyId;
            $userPIC->save();
        }

        // // Update phone if user already existed and phone is provided
        if (! empty($validated['phone']) && empty($participant->phone)) {
            $userPIC->phone = $validated['phone'];
            $userPIC->save();
        }



        $defaultTicketCategory = TicketCategory::where('event_id', $event->id)->value('id');

        // Create order
        $order = Order::create([
            'user_id' => $userPIC->id,
            'event_id' => $event->id,
            'status' => 'paid',
            'total_amount' => 0,
        ]);

        $start = Carbon::parse($event->start_time);
        $end   = Carbon::parse($event->end_time);

        for (
            $date = $start->copy();
            $date->lte($end);
            $date->addDay()
        ) {
            OrderItem::create([
                'order_id' => $order->id,
                'company_id' => $companyId,
                'event_date' => $date->copy(), // Carbon instance
                'ticket_category_id' => $defaultTicketCategory,
            ]);
        }

        // // Associate company (participant represents a company that can have many users)
        // $company = null;
        // if (! empty($validated['company_id'])) {
        //     $company = Company::find($validated['company_id']);
        // } elseif (! empty($validated['company_name'])) {
        //     $company = Company::firstOrCreate(['name' => $validated['company_name']]);
        // } elseif (Auth::user()->company) {
        //     $company = Auth::user()->company;
        // }

        // // Handle uploaded company logo if provided
        // if ($request->hasFile('company_logo') && $request->file('company_logo')->isValid()) {
        //     // Ensure a company exists to attach the logo to
        //     if (! $company) {
        //         $name = $validated['company_name'] ?? ($participant->name . ' Company');
        //         $company = Company::firstOrCreate(['name' => $name]);
        //     }

        //     $file = $request->file('company_logo');
        //     $path = $file->store('company_logos', 'public');
        //     $company->company_logo = $path;
        //     $company->save();
        // }

        // if ($company) {
        //     $participant->company_id = $company->id;
        //     $participant->save();
        // }

        // // Create order
        // $order = Order::create([
        //     'user_id' => $participant->id,
        //     'event_id' => $event->id,
        //     'status' => 'paid',
        //     'total_amount' => 0,
        // ]);

        // // Create order item
        // OrderItem::create([
        //     'order_id' => $order->id,
        //     'ticket_category_id' => $validated['ticket_category_id'],
        //     'price' => 0,
        //     // booking_code will be generated by model; copy status from order for reference
        //     'status' => $order->status,
        // ]);

        return redirect()->back()->with('success', 'Participant added successfully');
    }

    /**
     * User register to event.
     */
    public function registerToEvent(Request $request, $eventId)
    {
        $event = Event::find($eventId);
        $user = Auth::user();

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|email',
            'phone' => 'nullable|string|max:20',
            'ticket_category_id' => 'required|exists:ticket_categories,id',
        ]);

        // Verify organizer owns this event
        // if ($event->organizer_id != $user->organizer->id) {
        //     return response()->json(['error' => 'Unauthorized'], 403);
        // }

        // Create order
        $order = Order::create([
            'user_id' => $user->id,
            'event_id' => $event->id,
            'status' => 'paid',
            'total_amount' => 0,
        ]);

        // Create order item
        OrderItem::create([
            'order_id' => $order->id,
            'ticket_category_id' => $validated['ticket_category_id'],
            'price' => 0,
            'status' => $order->status,
        ]);

        return redirect()->back()->with('success', 'Participant registered successfully');
    }

    /**
     * Display participants for an event.
     */
    public function index(Event $event)
    {
        $user = Auth::user();
        $organizer = $user->organizer;

        abort_if($event->organizer_id != $organizer?->id, 403);

        $participants = Order::where('event_id', $event->id)
            ->with(['user.company', 'items.seat', 'items.category', 'items.company'])
            ->paginate(20)
            ->withQueryString();

        return Inertia::render('organizer/participants/index', [
            'event' => $event,
            'participants' => $participants,
        ]);
    }

    public function destroy($eventId, $orderId)
    {
        $user = Auth::user();
        $organizer = $user->organizer;
        $event = Event::where('id', $eventId)->firstOrFail();

        abort_if($event->organizer_id != $organizer?->id, 403);

        $participant = OrderItem::where('id', $orderId)->firstOrFail();


        $order = $participant->order;

        $order->delete();
        $participant->delete();

        return redirect()->back()->with('success', 'Participant deleted successfully');
    }

    /**
     * Export participants list.
     */
    public function export(Event $event)
    {
        $user = Auth::user();
        $organizer = $user->organizer;

        $participants = OrderItem::whereHas('order', function ($q) use ($event) {
            $q->where('event_id', $event->id);
        })
            ->with(['order.user', 'seat', 'category'])
            ->get();

        // Generate CSV
        $csv = "Name,Email,Phone,Ticket Category,Seat,Order Date\n";
        foreach ($participants as $participant) {
            $csv .= sprintf(
                '"%s","%s","%s","%s","%s","%s"' . "\n",
                $participant->order->user->name ?? 'N/A',
                $participant->order->user->email ?? 'N/A',
                'N/A',
                $participant->category->name ?? 'N/A',
                $participant->seat ? sprintf('%s-%s', $participant->seat->row_number, $participant->seat->seat_number) : 'N/A',
                $participant->created_at->format('Y-m-d H:i')
            );
        }

        return response($csv)
            ->header('Content-Type', 'text/csv')
            ->header('Content-Disposition', 'attachment; filename="participants-' . $event->id . '.csv"');
    }

    /**
     * Store a new participant from an order item (via modal form).
     */
    public function storeFromOrderItem(Request $request, Event $event, OrderItem $orderItem)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email',
            'phone' => 'nullable|string|max:20',
            'seat' => 'nullable|string|max:50',
            'user_id' => 'required|exists:users,id',
            'event_id' => 'required|exists:events,id',
        ]);

        $user = Auth::user();
        $organizer = $user->organizer;

        // Verify organizer owns this event
        if ($event->organizer_id != $organizer->id) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        // Find or create user by email for the participant
        $participant = User::firstOrCreate(
            ['email' => $validated['email']],
            [
                'name' => $validated['name'],
                'phone' => $validated['phone'] ?? null,
                'password' => Hash::make(Str::random(16)),
                'email_verified_at' => now(),
            ]
        );

        // Update phone if user already existed and phone is provided
        if (!empty($validated['phone']) && empty($participant->phone)) {
            $participant->phone = $validated['phone'];
            $participant->save();
        }

        // Create participant record
        $participantRecord = $orderItem->participant()->create([
            'event_id' => $validated['event_id'],
            'event_date' => $event->start_date ?? now(),
            'user_id' => $participant->id,
            'seat_id' => null, // Seat reference can be added if you have seat management
            'company_id' => $participant->company_id,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Participant added successfully',
            'data' => $participantRecord,
        ], 201);
    }

    /**
     * Delete a participant record.
     */
    public function destroyParticipant(Request $request, Event $event, Participant $participant)
    {
        // dd($event->id, $participant);
        $user = Auth::user();
        $organizer = $user->organizer;

        // Verify organizer owns this event
        if ($event->organizer_id != $organizer->id) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        // Verify participant belongs to this event
        if ($participant->event_id != $event->id) {
            return response()->json(['error' => 'Participant does not belong to this event'], 404);
        }

        $participantName = $participant->user?->name;
        $participant->delete();

        return response()->json([
            'success' => true,
            'message' => "Participant '$participantName' deleted successfully",
        ]);
    }

    /**
     * Update a participant record (inline edit from modal)
     */
    public function updateParticipant(Request $request, Event $event, Participant $participant)
    {
        $user = Auth::user();
        $organizer = $user->organizer;

        // Verify organizer owns this event
        if ($event->organizer_id != $organizer->id) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        // Verify participant belongs to this event
        if ($participant->event_id != $event->id) {
            return response()->json(['error' => 'Participant does not belong to this event'], 404);
        }

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . ($participant->user_id ?? 'NULL') . ',id',
            'phone' => 'nullable|string|max:20',
            'seat_id' => 'nullable|exists:event_seats,id',
        ]);

        // Update related user record (participant user)
        $userRecord = $participant->user;
        if ($userRecord) {
            $userRecord->name = $validated['name'];
            $userRecord->email = $validated['email'];
            $userRecord->phone = $validated['phone'] ?? $userRecord->phone;
            $userRecord->save();
        }

        // Update participant seat if provided
        if (array_key_exists('seat_id', $validated)) {
            $participant->seat_id = $validated['seat_id'];
        }

        $participant->save();

        return response()->json([
            'success' => true,
            'message' => 'Participant updated successfully',
            'data' => $participant->load('user', 'seat'),
        ]);
    }
}
